name: C++ Build and Test

on:
  workflow_call:
    inputs:
      source_directory:
        description: Source Directory
        required: true
        type: string
      use_lockfile:
        description: Use Existing Lockfile
        default: false
        required: false
        type: boolean
      os:
        description: Source Directory
        required: true
        type: string

jobs:
  build-and-test:
    runs-on: ${{ inputs.os }}

    defaults:
      run:
        working-directory: ${{ inputs.source_directory }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Conan
        uses: conan-io/setup-conan@v1

      - name: Unix Build
        if: ${{ runner.os != 'Windows' }}
        run: |
          conan profile detect --force

          conan build . \
            -o build_tests=True \
            -o run_tests=True \
            --build=missing \
            ${{ inputs.use_lockfile && '--lockfile=conan.lock' || '# do not use a lockfile' }}

      - name: Windows Build
        if: ${{ runner.os == 'Windows' }}
        run: |
          conan profile detect --force

          conan build . `
            -o build_tests=True `
            -o run_tests=True `
            --build=missing `
            ${{ inputs.use_lockfile && '--lockfile=conan.lock' || '# do not use a lockfile' }}

      - name: Upload Build Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: package-${{ inputs.os }}
          path: ${{ inputs.source_directory }}/build/
