name: C++ Lint (clang-format)

on:
  workflow_call:
    inputs:
      source_directory:
        description: Source Directory
        required: true
        type: string

jobs:
  clang-format-check:
    name: Check Formatting
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ${{ inputs.source_directory }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check Formatting
        run: |
          FILES=$(git ls-files '*.c' '*.cc' '*.cpp' '*.h' '*.hh' '*.hpp')
          [ -z "$FILES" ] && exit 0
          echo "$FILES" | xargs -r clang-format -style=LLVM -i
          git diff --exit-code
